name = "artwork-viewer"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build"
cwd = "."
main = "dist/index.html"

[build.upload]
format = "modules"
dir = "dist"

[env.production]
vars = { ENVIRONMENT = "production" }
